Repository fknives/AndroidTest-ShowCase, pull requests merged in 2022-02, with the labels that each got.

#57 Proof read robolectric instruction set
  app/src/robolectricTest/java/org/fnives/test/showcase/storage/favourite/CodeKataFavouriteContentLocalStorageInstrumentedTest.kt
  app/src/robolectricTest/java/org/fnives/test/showcase/storage/favourite/FavouriteContentLocalStorageImplInstrumentedTest.kt
  app/src/robolectricTest/java/org/fnives/test/showcase/ui/RobolectricAuthActivityInstrumentedTest.kt
  app/src/sharedTest/java/org/fnives/test/showcase/testutils/idling/MainDispatcherTestRule.kt
  app/src/test/java/org/fnives/test/showcase/testutils/TestMainDispatcher.kt
  codekata/core.again.instructionset.md
  codekata/robolectric.instructionset.md
Labels: documentation, enhancement

#59 Issue#48 Update readme
  README.md
  app/build.gradle
Labels: documentation

#62 Issue#61 Update robolectric version to 4.7
  gradlescripts/versions.gradle
Labels: bug
