Repository fknives/AndroidTest-ShowCase, pull requests merged in 2022-04, with the labels that each got.

#71 Fixes in ViewModel Instruction set
  codekata/viewmodel.instructionset.md
Labels: documentation

#70 issue#14 Write shared test instructionset
  README.md
  app/src/androidTest/java/org/fnives/test/showcase/endtoend/LoginLogoutEndToEndTest.kt
  app/src/androidTest/java/org/fnives/test/showcase/endtoend/MyTestSuit.kt
  app/src/sharedTest/java/org/fnives/test/showcase/testutils/configuration/ServerTypeConfiguration.kt
  app/src/sharedTest/java/org/fnives/test/showcase/testutils/configuration/SnackBarTestRule.kt
  app/src/sharedTest/java/org/fnives/test/showcase/ui/login/codekata/CodeKataAuthActivitySharedTest.kt
  app/src/sharedTest/java/org/fnives/test/showcase/ui/login/codekata/CodeKataSharedRobotTest.kt
  app/src/sharedTest/java/org/fnives/test/showcase/ui/login/codekata/rule/dispatcher/CodeKataMainDispatcherRule.kt
  app/src/sharedTest/java/org/fnives/test/showcase/ui/login/codekata/rule/dispatcher/PlainMainDispatcherRule.kt
  app/src/sharedTest/java/org/fnives/test/showcase/ui/login/codekata/rule/intent/CodeKataIntentInitRule.kt
  app/src/sharedTest/java/org/fnives/test/showcase/ui/login/codekata/rule/intent/PlainIntentInitRule.kt
  codekata/sharedtests.instructionset
  codekata/sharedtests.instructionset.md
  gradlescripts/versions.gradle
Labels: documentation, Priority

#68 Compose
  README.md
  app/build.gradle
  app/src/androidTest/java/org/fnives/test/showcase/ui/AuthComposeInstrumentedTest.kt
  app/src/androidTest/java/org/fnives/test/showcase/ui/ComposeLoginRobot.kt
  app/src/androidTest/java/org/fnives/test/showcase/ui/ComposeNavigationRobot.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fnives/test/showcase/compose/ComposeActivity.kt
  app/src/main/java/org/fnives/test/showcase/compose/screen/AppNavigation.kt
  app/src/main/java/org/fnives/test/showcase/compose/screen/auth/AuthScreen.kt
  app/src/main/java/org/fnives/test/showcase/compose/screen/auth/AuthScreenState.kt
  app/src/main/java/org/fnives/test/showcase/compose/screen/home/HomeScreen.kt
  app/src/main/java/org/fnives/test/showcase/compose/screen/home/HomeScreenState.kt
  app/src/main/java/org/fnives/test/showcase/compose/screen/splash/SplashScreen.kt
  app/src/main/res/drawable/show_password.xml
  app/src/sharedTest/java/org/fnives/test/showcase/testutils/MockServerScenarioSetupResetingTestRule.kt
  app/src/sharedTest/java/org/fnives/test/showcase/testutils/idling/DispatcherTestRule.kt
  codekata/compose.instructionset.md
  gradlescripts/versions.gradle
Labels: documentation, enhancement

#75 Issue#74 Attempt to integrate testing on emulator
  .github/workflows/pull-request-jobs.yml
  app/src/main/java/org/fnives/test/showcase/compose/screen/splash/SplashScreen.kt
Labels: enhancement

#77 Fix back navigation in Compose implementation
  app/src/main/java/org/fnives/test/showcase/compose/screen/AppNavigation.kt
  detekt/detekt.yml
Labels: bug

#79 Differentiate compose launcher
  app/src/main/AndroidManifest.xml
  app/src/main/ic_compose_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_compose_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_compose_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_compose_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_compose_launcher.png
  app/src/main/res/mipmap-hdpi/ic_compose_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_compose_launcher.png
  app/src/main/res/mipmap-mdpi/ic_compose_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_compose_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_compose_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_compose_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_compose_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_compose_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_compose_launcher_round.png
  app/src/main/res/values/strings.xml
Labels: enhancement
